### ISSUE TITLE
Update of card info after failed payment not possible when stock is unavailable

### ISSUE THREAD

**Issue by joenweidemann** [Prospress/woocommerce-subscriptions-do-not-reduce-stock-on-renewal#1]
First thanks for this plugin without which we would have huge problems every month.

We run a Gym Membership with limited number of places for different memberships. Without your plugin all payments would fail during the monthly renewals for a membership type that is sold out and not taking on new memberships. But renewals should work for those who have secured a place. With your plugin it does. Thanks.

But if a payment fails (declined card etc.) neither automatic payment re-tries nor a manual login and update of card details by the user works. I guess when renewing it calls the product availablity check in a way that is not fixed by your plugin.

Are you able to fixe these cases too?

**Comment by NickGreen** [comment]
I believe the issue here is the result of open [PR #3016](https://github.com/Prospress/woocommerce-subscriptions/pull/3016) in the WC Subscriptions codebase. Closing this here, since it's a WC Subscriptions issue.
